// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Title string `json:"title"`
}

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}

type UpdateTodoInput struct {
	ID    string  `json:"id"`
	Title *string `json:"title,omitempty"`
	Done  *bool   `json:"done,omitempty"`
}
